export const MOCK_LOANS = [
  // --- LOANS GIVEN (ASSETS) ---
  {
    "id": "mock_01",
    "localid": "AST-001",
    "name": null,
    "date": "2026-01-15T08:00:00.000Z",
    "status": "OPEN",
    "contracttype": "LOAN_GIVEN",
    "partnername": "SolarLogistics",
    "partnercode": "SLOG",
    "duedate": "2026-02-15T08:00:00.000Z",
    "implied_interest_rate": 5.5,
    "installment_count": 12,
    "installment_done": 1,
    "installment_interval": 30,
    "loan_strategy": "DEDUCING_INTEREST",
    "total_amount": 1200000,
    "currency": "ICA",
    "operation_type": "UNKNOWN"
  },
  {
    "id": "mock_02",
    "localid": "AST-002",
    "name": "Quick Liquidity",
    "date": "2026-02-01T10:30:00.000Z",
    "status": "OPEN",
    "contracttype": "LOAN_GIVEN",
    "partnername": "RedDwarf Mining",
    "partnercode": "RDM",
    "duedate": "2026-02-08T10:30:00.000Z",
    "implied_interest_rate": 10,
    "installment_count": 4,
    "installment_done": 0,
    "installment_interval": 7,
    "loan_strategy": "STABLE_INTEREST",
    "total_amount": 55000,
    "currency": "ICA",
    "operation_type": "UNKNOWN"
  },
  {
    "id": "mock_03",
    "localid": "AST-003",
    "name": null,
    "date": "2025-11-20T09:00:00.000Z",
    "status": "PARTIALLY_FULFILLED",
    "contracttype": "LOAN_GIVEN",
    "partnername": "Helix Chem",
    "partnercode": "HELX",
    "duedate": "2026-02-20T09:00:00.000Z",
    "implied_interest_rate": 8.2,
    "installment_count": 24,
    "installment_done": 8,
    "installment_interval": 14,
    "loan_strategy": "DEDUCING_INTEREST",
    "total_amount": 4500000,
    "currency": "ICA",
    "operation_type": "UNKNOWN"
  },
  {
    "id": "mock_04",
    "localid": "AST-004",
    "name": null,
    "date": "2026-01-05T14:15:00.000Z",
    "status": "BREACHED",
    "contracttype": "LOAN_GIVEN",
    "partnername": "Void Runners",
    "partnercode": "VOID",
    "duedate": "2026-01-28T14:15:00.000Z",
    "implied_interest_rate": 15,
    "installment_count": 6,
    "installment_done": 1,
    "installment_interval": 7,
    "loan_strategy": "STABLE_INTEREST",
    "total_amount": 250000,
    "currency": "ICA",
    "operation_type": "UNKNOWN"
  },
  {
    "id": "mock_05",
    "localid": "AST-005",
    "name": null,
    "date": "2025-12-01T12:00:00.000Z",
    "status": "FULFILLED",
    "contracttype": "LOAN_GIVEN",
    "partnername": "Alpha Centauri",
    "partnercode": "ALPC",
    "duedate": "2026-01-30T12:00:00.000Z",
    "implied_interest_rate": 6,
    "installment_count": 10,
    "installment_done": 10,
    "installment_interval": 10,
    "loan_strategy": "DEDUCING_INTEREST",
    "total_amount": 800000,
    "currency": "ICA",
    "operation_type": "UNKNOWN"
  },
  {
    "id": "mock_06",
    "localid": "AST-006",
    "name": null,
    "date": "2026-02-03T08:45:00.000Z",
    "status": "OPEN",
    "contracttype": "LOAN_GIVEN",
    "partnername": "Orbital Fab",
    "partnercode": "ORBF",
    "duedate": "2026-03-03T08:45:00.000Z",
    "implied_interest_rate": 4.5,
    "installment_count": 12,
    "installment_done": 0,
    "installment_interval": 30,
    "loan_strategy": "DEDUCING_INTEREST",
    "total_amount": 2000000,
    "currency": "ICA",
    "operation_type": "UNKNOWN"
  },
  {
    "id": "mock_07",
    "localid": "AST-007",
    "name": null,
    "date": "2026-01-20T16:20:00.000Z",
    "status": "PARTIALLY_FULFILLED",
    "contracttype": "LOAN_GIVEN",
    "partnername": "TerraFormers",
    "partnercode": "TERR",
    "duedate": "2026-02-10T16:20:00.000Z",
    "implied_interest_rate": 12,
    "installment_count": 8,
    "installment_done": 3,
    "installment_interval": 14,
    "loan_strategy": "STABLE_INTEREST",
    "total_amount": 600000,
    "currency": "ICA",
    "operation_type": "UNKNOWN"
  },
  {
    "id": "mock_08",
    "localid": "AST-008",
    "name": null,
    "date": "2025-10-15T11:00:00.000Z",
    "status": "CLOSED",
    "contracttype": "LOAN_GIVEN",
    "partnername": "Lunar Base 7",
    "partnercode": "LB7",
    "duedate": "2026-01-15T11:00:00.000Z",
    "implied_interest_rate": 5,
    "installment_count": 6,
    "installment_done": 6,
    "installment_interval": 30,
    "loan_strategy": "DEDUCING_INTEREST",
    "total_amount": 150000,
    "currency": "ICA",
    "operation_type": "UNKNOWN"
  },
  {
    "id": "mock_09",
    "localid": "AST-009",
    "name": null,
    "date": "2026-02-04T05:00:00.000Z",
    "status": "OPEN",
    "contracttype": "LOAN_GIVEN",
    "partnername": "New Horizons",
    "partnercode": "NHOZ",
    "duedate": "2026-02-11T05:00:00.000Z",
    "implied_interest_rate": 20,
    "installment_count": 4,
    "installment_done": 0,
    "installment_interval": 7,
    "loan_strategy": "STABLE_INTEREST",
    "total_amount": 100000,
    "currency": "ICA",
    "operation_type": "UNKNOWN"
  },
  {
    "id": "mock_10",
    "localid": "AST-010",
    "name": null,
    "date": "2026-01-25T13:30:00.000Z",
    "status": "OPEN",
    "contracttype": "LOAN_GIVEN",
    "partnername": "Star Freight",
    "partnercode": "STRF",
    "duedate": "2026-02-25T13:30:00.000Z",
    "implied_interest_rate": 7.5,
    "installment_count": 24,
    "installment_done": 1,
    "installment_interval": 30,
    "loan_strategy": "DEDUCING_INTEREST",
    "total_amount": 5000000,
    "currency": "ICA",
    "operation_type": "UNKNOWN"
  },
  {
    "id": "mock_11",
    "localid": "AST-011",
    "name": null,
    "date": "2026-01-10T09:15:00.000Z",
    "status": "PARTIALLY_FULFILLED",
    "contracttype": "LOAN_GIVEN",
    "partnername": "Cosmic Ray",
    "partnercode": "CRAY",
    "duedate": "2026-02-10T09:15:00.000Z",
    "implied_interest_rate": 9,
    "installment_count": 12,
    "installment_done": 2,
    "installment_interval": 15,
    "loan_strategy": "STABLE_INTEREST",
    "total_amount": 750000,
    "currency": "ICA",
    "operation_type": "UNKNOWN"
  },
  {
    "id": "mock_12",
    "localid": "AST-012",
    "name": null,
    "date": "2026-01-30T15:45:00.000Z",
    "status": "OPEN",
    "contracttype": "LOAN_GIVEN",
    "partnername": "Nebula Gas",
    "partnercode": "NEBG",
    "duedate": "2026-02-14T15:45:00.000Z",
    "implied_interest_rate": 6.5,
    "installment_count": 6,
    "installment_done": 0,
    "installment_interval": 14,
    "loan_strategy": "DEDUCING_INTEREST",
    "total_amount": 300000,
    "currency": "ICA",
    "operation_type": "UNKNOWN"
  },
  {
    "id": "mock_13",
    "localid": "AST-013",
    "name": null,
    "date": "2025-12-15T10:00:00.000Z",
    "status": "BREACHED",
    "contracttype": "LOAN_GIVEN",
    "partnername": "Dark Matter Inc",
    "partnercode": "DMAT",
    "duedate": "2026-01-15T10:00:00.000Z",
    "implied_interest_rate": 18,
    "installment_count": 12,
    "installment_done": 2,
    "installment_interval": 30,
    "loan_strategy": "STABLE_INTEREST",
    "total_amount": 120000,
    "currency": "ICA",
    "operation_type": "UNKNOWN"
  },
  {
    "id": "mock_14",
    "localid": "AST-014",
    "name": null,
    "date": "2026-01-01T08:00:00.000Z",
    "status": "PARTIALLY_FULFILLED",
    "contracttype": "LOAN_GIVEN",
    "partnername": "Solar Winds",
    "partnercode": "SWND",
    "duedate": "2026-02-01T08:00:00.000Z",
    "implied_interest_rate": 4,
    "installment_count": 36,
    "installment_done": 4,
    "installment_interval": 30,
    "loan_strategy": "DEDUCING_INTEREST",
    "total_amount": 10000000,
    "currency": "ICA",
    "operation_type": "UNKNOWN"
  },
  {
    "id": "mock_15",
    "localid": "AST-015",
    "name": null,
    "date": "2026-02-02T11:20:00.000Z",
    "status": "OPEN",
    "contracttype": "LOAN_GIVEN",
    "partnername": "Titan Heavy",
    "partnercode": "TTHE",
    "duedate": "2026-02-09T11:20:00.000Z",
    "implied_interest_rate": 8,
    "installment_count": 8,
    "installment_done": 0,
    "installment_interval": 7,
    "loan_strategy": "STABLE_INTEREST",
    "total_amount": 400000,
    "currency": "ICA",
    "operation_type": "UNKNOWN"
  },
  {
    "id": "mock_16",
    "localid": "AST-016",
    "name": null,
    "date": "2026-01-18T14:00:00.000Z",
    "status": "PARTIALLY_FULFILLED",
    "contracttype": "LOAN_GIVEN",
    "partnername": "Asteroid Miners",
    "partnercode": "AMNR",
    "duedate": "2026-02-18T14:00:00.000Z",
    "implied_interest_rate": 10.5,
    "installment_count": 10,
    "installment_done": 3,
    "installment_interval": 30,
    "loan_strategy": "DEDUCING_INTEREST",
    "total_amount": 2200000,
    "currency": "ICA",
    "operation_type": "UNKNOWN"
  },
  {
    "id": "mock_17",
    "localid": "AST-017",
    "name": null,
    "date": "2025-11-30T09:30:00.000Z",
    "status": "FULFILLED",
    "contracttype": "LOAN_GIVEN",
    "partnername": "Comet Express",
    "partnercode": "CEXP",
    "duedate": "2026-01-30T09:30:00.000Z",
    "implied_interest_rate": 7,
    "installment_count": 8,
    "installment_done": 8,
    "installment_interval": 14,
    "loan_strategy": "STABLE_INTEREST",
    "total_amount": 350000,
    "currency": "ICA",
    "operation_type": "UNKNOWN"
  },
  {
    "id": "mock_18",
    "localid": "AST-018",
    "name": null,
    "date": "2026-02-01T16:00:00.000Z",
    "status": "OPEN",
    "contracttype": "LOAN_GIVEN",
    "partnername": "Galactic Trade",
    "partnercode": "GTRD",
    "duedate": "2026-02-15T16:00:00.000Z",
    "implied_interest_rate": 5.5,
    "installment_count": 6,
    "installment_done": 0,
    "installment_interval": 14,
    "loan_strategy": "DEDUCING_INTEREST",
    "total_amount": 900000,
    "currency": "ICA",
    "operation_type": "UNKNOWN"
  },
  {
    "id": "mock_19",
    "localid": "AST-019",
    "name": null,
    "date": "2026-01-12T10:45:00.000Z",
    "status": "PARTIALLY_FULFILLED",
    "contracttype": "LOAN_GIVEN",
    "partnername": "Starlight Energy",
    "partnercode": "SLEN",
    "duedate": "2026-02-12T10:45:00.000Z",
    "implied_interest_rate": 11,
    "installment_count": 12,
    "installment_done": 4,
    "installment_interval": 30,
    "loan_strategy": "STABLE_INTEREST",
    "total_amount": 1800000,
    "currency": "ICA",
    "operation_type": "UNKNOWN"
  },
  {
    "id": "mock_20",
    "localid": "AST-020",
    "name": null,
    "date": "2026-01-28T13:15:00.000Z",
    "status": "OPEN",
    "contracttype": "LOAN_GIVEN",
    "partnername": "Quantum Leap",
    "partnercode": "QLEP",
    "duedate": "2026-02-04T13:15:00.000Z",
    "implied_interest_rate": 15,
    "installment_count": 4,
    "installment_done": 1,
    "installment_interval": 7,
    "loan_strategy": "DEDUCING_INTEREST",
    "total_amount": 650000,
    "currency": "ICA",
    "operation_type": "UNKNOWN"
  },

  // --- LOANS TAKEN (LIABILITIES) ---
  {
    "id": "mock_21",
    "localid": "LIA-001",
    "name": "Fleet Expansion",
    "date": "2026-01-10T09:00:00.000Z",
    "status": "OPEN",
    "contracttype": "LOAN_TAKEN",
    "partnername": "Interstellar Bank",
    "partnercode": "ISBK",
    "duedate": "2026-02-10T09:00:00.000Z",
    "implied_interest_rate": 4.2,
    "installment_count": 24,
    "installment_done": 2,
    "installment_interval": 30,
    "loan_strategy": "DEDUCING_INTEREST",
    "total_amount": 5000000,
    "currency": "ICA",
    "operation_type": "UNKNOWN"
  },
  {
    "id": "mock_22",
    "localid": "LIA-002",
    "name": null,
    "date": "2026-02-01T14:30:00.000Z",
    "status": "OPEN",
    "contracttype": "LOAN_TAKEN",
    "partnername": "MioandMeow",
    "partnercode": "MNME",
    "duedate": "2026-02-08T14:30:00.000Z",
    "implied_interest_rate": 12,
    "installment_count": 10,
    "installment_done": 0,
    "installment_interval": 7,
    "loan_strategy": "STABLE_INTEREST",
    "total_amount": 3360000,
    "currency": "ICA",
    "operation_type": "UNKNOWN"
  },
  {
    "id": "mock_23",
    "localid": "LIA-003",
    "name": null,
    "date": "2026-01-20T11:00:00.000Z",
    "status": "PARTIALLY_FULFILLED",
    "contracttype": "LOAN_TAKEN",
    "partnername": "United Systems",
    "partnercode": "UNIS",
    "duedate": "2026-02-20T11:00:00.000Z",
    "implied_interest_rate": 8.5,
    "installment_count": 12,
    "installment_done": 3,
    "installment_interval": 30,
    "loan_strategy": "DEDUCING_INTEREST",
    "total_amount": 1200000,
    "currency": "ICA",
    "operation_type": "UNKNOWN"
  },
  {
    "id": "mock_24",
    "localid": "LIA-004",
    "name": "Emergency Repairs",
    "date": "2026-02-03T07:45:00.000Z",
    "status": "OPEN",
    "contracttype": "LOAN_TAKEN",
    "partnername": "FixIt Fast",
    "partnercode": "FIXT",
    "duedate": "2026-02-10T07:45:00.000Z",
    "implied_interest_rate": 25,
    "installment_count": 2,
    "installment_done": 0,
    "installment_interval": 7,
    "loan_strategy": "STABLE_INTEREST",
    "total_amount": 50000,
    "currency": "ICA",
    "operation_type": "UNKNOWN"
  },
  {
    "id": "mock_25",
    "localid": "LIA-005",
    "name": null,
    "date": "2025-12-05T16:00:00.000Z",
    "status": "BREACHED",
    "contracttype": "LOAN_TAKEN",
    "partnername": "Shark Capital",
    "partnercode": "SHRK",
    "duedate": "2026-01-05T16:00:00.000Z",
    "implied_interest_rate": 30,
    "installment_count": 8,
    "installment_done": 2,
    "installment_interval": 14,
    "loan_strategy": "STABLE_INTEREST",
    "total_amount": 200000,
    "currency": "ICA",
    "operation_type": "UNKNOWN"
  },
  {
    "id": "mock_26",
    "localid": "LIA-006",
    "name": null,
    "date": "2026-01-15T12:30:00.000Z",
    "status": "PARTIALLY_FULFILLED",
    "contracttype": "LOAN_TAKEN",
    "partnername": "Colonial Trust",
    "partnercode": "COTR",
    "duedate": "2026-02-15T12:30:00.000Z",
    "implied_interest_rate": 6,
    "installment_count": 18,
    "installment_done": 4,
    "installment_interval": 30,
    "loan_strategy": "DEDUCING_INTEREST",
    "total_amount": 2500000,
    "currency": "ICA",
    "operation_type": "UNKNOWN"
  },
  {
    "id": "mock_27",
    "localid": "LIA-007",
    "name": null,
    "date": "2026-01-25T10:15:00.000Z",
    "status": "OPEN",
    "contracttype": "LOAN_TAKEN",
    "partnername": "Omega Corp",
    "partnercode": "OMEG",
    "duedate": "2026-02-08T10:15:00.000Z",
    "implied_interest_rate": 9,
    "installment_count": 6,
    "installment_done": 1,
    "installment_interval": 14,
    "loan_strategy": "STABLE_INTEREST",
    "total_amount": 400000,
    "currency": "ICA",
    "operation_type": "UNKNOWN"
  },
  {
    "id": "mock_28",
    "localid": "LIA-008",
    "name": null,
    "date": "2025-11-10T08:00:00.000Z",
    "status": "FULFILLED",
    "contracttype": "LOAN_TAKEN",
    "partnername": "Deep Space Nine",
    "partnercode": "DS9",
    "duedate": "2026-01-10T08:00:00.000Z",
    "implied_interest_rate": 7,
    "installment_count": 4,
    "installment_done": 4,
    "installment_interval": 30,
    "loan_strategy": "DEDUCING_INTEREST",
    "total_amount": 100000,
    "currency": "ICA",
    "operation_type": "UNKNOWN"
  },
  {
    "id": "mock_29",
    "localid": "LIA-009",
    "name": null,
    "date": "2026-02-02T15:00:00.000Z",
    "status": "OPEN",
    "contracttype": "LOAN_TAKEN",
    "partnername": "Vanguard Systems",
    "partnercode": "VANG",
    "duedate": "2026-02-16T15:00:00.000Z",
    "implied_interest_rate": 5,
    "installment_count": 12,
    "installment_done": 0,
    "installment_interval": 14,
    "loan_strategy": "DEDUCING_INTEREST",
    "total_amount": 1500000,
    "currency": "ICA",
    "operation_type": "UNKNOWN"
  },
  {
    "id": "mock_30",
    "localid": "LIA-010",
    "name": null,
    "date": "2026-01-08T09:45:00.000Z",
    "status": "PARTIALLY_FULFILLED",
    "contracttype": "LOAN_TAKEN",
    "partnername": "Helios Mining",
    "partnercode": "HMIN",
    "duedate": "2026-02-08T09:45:00.000Z",
    "implied_interest_rate": 10,
    "installment_count": 20,
    "installment_done": 6,
    "installment_interval": 30,
    "loan_strategy": "STABLE_INTEREST",
    "total_amount": 3000000,
    "currency": "ICA",
    "operation_type": "UNKNOWN"
  },
  {
    "id": "mock_31",
    "localid": "LIA-011",
    "name": null,
    "date": "2026-01-22T14:20:00.000Z",
    "status": "OPEN",
    "contracttype": "LOAN_TAKEN",
    "partnername": "Orion Syndicate",
    "partnercode": "ORIN",
    "duedate": "2026-02-05T14:20:00.000Z",
    "implied_interest_rate": 14,
    "installment_count": 8,
    "installment_done": 2,
    "installment_interval": 7,
    "loan_strategy": "STABLE_INTEREST",
    "total_amount": 800000,
    "currency": "ICA",
    "operation_type": "UNKNOWN"
  },
  {
    "id": "mock_32",
    "localid": "LIA-012",
    "name": null,
    "date": "2025-12-20T11:50:00.000Z",
    "status": "BREACHED",
    "contracttype": "LOAN_TAKEN",
    "partnername": "Red Planet Inc",
    "partnercode": "RPLT",
    "duedate": "2026-01-20T11:50:00.000Z",
    "implied_interest_rate": 22,
    "installment_count": 12,
    "installment_done": 3,
    "installment_interval": 30,
    "loan_strategy": "DEDUCING_INTEREST",
    "total_amount": 180000,
    "currency": "ICA",
    "operation_type": "UNKNOWN"
  },
  {
    "id": "mock_33",
    "localid": "LIA-013",
    "name": null,
    "date": "2026-01-18T08:30:00.000Z",
    "status": "PARTIALLY_FULFILLED",
    "contracttype": "LOAN_TAKEN",
    "partnername": "Sky High Logistics",
    "partnercode": "SHLG",
    "duedate": "2026-02-18T08:30:00.000Z",
    "implied_interest_rate": 7.8,
    "installment_count": 10,
    "installment_done": 4,
    "installment_interval": 30,
    "loan_strategy": "STABLE_INTEREST",
    "total_amount": 950000,
    "currency": "ICA",
    "operation_type": "UNKNOWN"
  },
  {
    "id": "mock_34",
    "localid": "LIA-014",
    "name": null,
    "date": "2026-02-04T06:00:00.000Z",
    "status": "OPEN",
    "contracttype": "LOAN_TAKEN",
    "partnername": "Terra Nova",
    "partnercode": "TNOV",
    "duedate": "2026-02-11T06:00:00.000Z",
    "implied_interest_rate": 6,
    "installment_count": 6,
    "installment_done": 0,
    "installment_interval": 7,
    "loan_strategy": "DEDUCING_INTEREST",
    "total_amount": 275000,
    "currency": "ICA",
    "operation_type": "UNKNOWN"
  },
  {
    "id": "mock_35",
    "localid": "LIA-015",
    "name": null,
    "date": "2026-01-30T13:45:00.000Z",
    "status": "OPEN",
    "contracttype": "LOAN_TAKEN",
    "partnername": "Eclipse Energy",
    "partnercode": "ECLP",
    "duedate": "2026-02-13T13:45:00.000Z",
    "implied_interest_rate": 11.5,
    "installment_count": 8,
    "installment_done": 0,
    "installment_interval": 14,
    "loan_strategy": "STABLE_INTEREST",
    "total_amount": 720000,
    "currency": "ICA",
    "operation_type": "UNKNOWN"
  },
  {
    "id": "mock_36",
    "localid": "LIA-016",
    "name": null,
    "date": "2026-01-14T10:10:00.000Z",
    "status": "PARTIALLY_FULFILLED",
    "contracttype": "LOAN_TAKEN",
    "partnername": "Fusion Drive",
    "partnercode": "FDRV",
    "duedate": "2026-02-14T10:10:00.000Z",
    "implied_interest_rate": 9.2,
    "installment_count": 12,
    "installment_done": 3,
    "installment_interval": 30,
    "loan_strategy": "DEDUCING_INTEREST",
    "total_amount": 1600000,
    "currency": "ICA",
    "operation_type": "UNKNOWN"
  },
  {
    "id": "mock_37",
    "localid": "LIA-017",
    "name": null,
    "date": "2026-02-01T17:00:00.000Z",
    "status": "OPEN",
    "contracttype": "LOAN_TAKEN",
    "partnername": "Gravity Well",
    "partnercode": "GWEL",
    "duedate": "2026-02-15T17:00:00.000Z",
    "implied_interest_rate": 13,
    "installment_count": 4,
    "installment_done": 0,
    "installment_interval": 14,
    "loan_strategy": "STABLE_INTEREST",
    "total_amount": 450000,
    "currency": "ICA",
    "operation_type": "UNKNOWN"
  },
  {
    "id": "mock_38",
    "localid": "LIA-018",
    "name": null,
    "date": "2025-12-28T09:00:00.000Z",
    "status": "FULFILLED",
    "contracttype": "LOAN_TAKEN",
    "partnername": "Halo Tech",
    "partnercode": "HTEC",
    "duedate": "2026-01-28T09:00:00.000Z",
    "implied_interest_rate": 5,
    "installment_count": 4,
    "installment_done": 4,
    "installment_interval": 30,
    "loan_strategy": "DEDUCING_INTEREST",
    "total_amount": 125000,
    "currency": "ICA",
    "operation_type": "UNKNOWN"
  },
  {
    "id": "mock_39",
    "localid": "LIA-019",
    "name": null,
    "date": "2026-01-27T12:30:00.000Z",
    "status": "OPEN",
    "contracttype": "LOAN_TAKEN",
    "partnername": "Ion Systems",
    "partnercode": "IONS",
    "duedate": "2026-02-10T12:30:00.000Z",
    "implied_interest_rate": 8,
    "installment_count": 10,
    "installment_done": 1,
    "installment_interval": 14,
    "loan_strategy": "STABLE_INTEREST",
    "total_amount": 550000,
    "currency": "ICA",
    "operation_type": "UNKNOWN"
  },
  {
    "id": "mock_40",
    "localid": "LIA-020",
    "name": null,
    "date": "2026-02-03T15:15:00.000Z",
    "status": "OPEN",
    "contracttype": "LOAN_TAKEN",
    "partnername": "Jupiter Gas",
    "partnercode": "JGAS",
    "duedate": "2026-02-17T15:15:00.000Z",
    "implied_interest_rate": 10,
    "installment_count": 6,
    "installment_done": 0,
    "installment_interval": 14,
    "loan_strategy": "DEDUCING_INTEREST",
    "total_amount": 850000,
    "currency": "ICA",
    "operation_type": "UNKNOWN"
  },
  {
    "id": "mock_41",
    "localid": "LIA-021",
    "name": null,
    "date": "2026-01-05T08:00:00.000Z",
    "status": "BREACHED",
    "contracttype": "LOAN_TAKEN",
    "partnername": "Kepler Dynamics",
    "partnercode": "KDYN",
    "duedate": "2026-01-20T08:00:00.000Z",
    "implied_interest_rate": 20,
    "installment_count": 8,
    "installment_done": 1,
    "installment_interval": 14,
    "loan_strategy": "STABLE_INTEREST",
    "total_amount": 225000,
    "currency": "ICA",
    "operation_type": "UNKNOWN"
  },
  {
    "id": "mock_42",
    "localid": "LIA-022",
    "name": null,
    "date": "2026-01-15T11:45:00.000Z",
    "status": "PARTIALLY_FULFILLED",
    "contracttype": "LOAN_TAKEN",
    "partnername": "Lyra Constellations",
    "partnercode": "LYRA",
    "duedate": "2026-02-15T11:45:00.000Z",
    "implied_interest_rate": 7.2,
    "installment_count": 24,
    "installment_done": 5,
    "installment_interval": 30,
    "loan_strategy": "DEDUCING_INTEREST",
    "total_amount": 4200000,
    "currency": "ICA",
    "operation_type": "UNKNOWN"
  }
];